# Generated by Django 3.0.3 on 2020-02-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(default='', max_length=10),
        ),
    ]
