# Generated by Django 3.0.3 on 2020-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='/tutor/static/default_profile_pic.png', upload_to='profile_picture'),
        ),
    ]
