# Generated by Django 3.0.3 on 2020-03-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_profile_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='/tutor/static/tutor/default_profile_pic.png', upload_to='profile_picture'),
        ),
    ]
