# Generated by Django 3.0.4 on 2020-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20200327_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='/media/profile_picture/default_profile_pic.png', upload_to='media/profile_picture'),
        ),
    ]
