# Generated by Django 3.0.2 on 2020-03-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20200327_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='subject',
            field=models.ForeignKey(default='None', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(choices=[('none', 'None'), ('african-american studies', 'African-American & African Studies'), ('anthropology', 'Anthropology'), ('astronomy', 'Astronomy'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('economics', 'Economics'), ('french', 'French'), ('german', 'German'), ('physics', 'Physics'), ('mathematics', 'Mathematics')], default='', max_length=30),
        ),
    ]
