# Generated by Django 3.0.2 on 2020-03-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20200327_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='subject',
            field=models.CharField(choices=[('none', 'None'), ('african-american studies', 'African-American & African Studies'), ('anthropology', 'Anthropology'), ('astronomy', 'Astronomy'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('economics', 'Economics'), ('french', 'French'), ('german', 'German'), ('physics', 'Physics'), ('mathematics', 'Mathematics')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=30),
        ),
    ]
