# Generated by Django 3.0.2 on 2020-03-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_job_isconfirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.AddField(
            model_name='job',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile', to='tutor.Profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='tutor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TutorProfile', to='tutor.Profile'),
        ),
    ]
