# Generated by Django 3.0.2 on 2020-03-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20200321_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
    ]
