# Generated by Django 3.0.2 on 2020-03-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20200327_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='subject',
            field=models.CharField(choices=[('None', 'None'), ('African-american studies', 'African-American & African Studies'), ('Anthropology', 'Anthropology'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('French', 'French'), ('German', 'German'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics')], default='None', max_length=200),
        ),
    ]
