# Generated by Django 3.0.4 on 2020-03-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20200328_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default_profile_pic.png', upload_to='media/profile_picture'),
        ),
    ]
