# Generated by Django 3.0.2 on 2020-03-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='course',
            field=models.CharField(default='', help_text='Ex: ECON 2010, MATH 1010', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('None', 'None'), ('Alderman Library', 'Alderman Library'), ('Aquatic and Fitness Center', 'Aquatic and Fitness Center'), ('Astronomy Building', 'Astronomy Building'), ('Birdwood Golf Course', 'Birdwood Golf Course'), ('Bayly Building', 'Bayly Building'), ('Brooks Hall (first floor and basement only)', 'Brooks Hall (first floor and basement only)'), ('Bryan Hall', 'Bryan Hall'), ('Brown College Library', 'Brown College Library'), ('Bryant Hall', 'Bryant Hall'), ('New Cabell Hall', 'New Cabell Hall'), ('Campbell Hall', 'Campbell Hall'), ('Cauthen House', 'Cauthen House'), ('Chemical Engineering Building', 'Chemical Engineering Building'), ('Claude Moore Nursing', 'Claude Moore Nursing'), ('Cobb Hall', 'Cobb Hall'), ('Cocke Hall', 'Cocke Hall'), ('Chemistry Building (key needed for elevator)', 'Chemistry Building (key needed for elevator)'), ('Clark Hall', 'Clark Hall'), ('Clemons Library', 'Clemons Library'), ('Dell 1', 'Dell 1'), ('Dell 2', 'Dell 2'), ('Dawsons Row Residence 1', 'Dawsons Row Residence 1'), ('Drama Education Building (key needed for elevator)', 'Drama Education Building (key needed for elevator)'), ('Hospital West, Davis Wing', 'Hospital West, Davis Wing'), ('Fayerweather Hall', 'Fayerweather Hall'), ('French House', 'French House'), ('Gibson Hall', 'Gibson Hall'), ('Gilmer Hall', 'Gilmer Hall'), ('Darden School', 'Darden School'), ('Halsey Hall', 'Halsey Hall'), ('Hotel D, East Range', 'Hotel D,East Range'), ('Jordan Hall', 'Jordan Hall'), ('Kerchof Hall (first floor only)', 'Kerchof Hall'), ('Levering Hall', 'Levering Hall'), ('Lambeth House', 'Lambeth House'), ('Lower West Oval Room, Rotunda', 'Lower West Oval Room, Rotunda'), ('McLeod Hall', 'McLeod Hall'), ('Mechanical Engineering Building', 'Mechanical Engineering Building'), ('Old Medical School', 'Old Medical School'), ('Memorial Gymnasium', 'Memorial Gymnasium'), ('Multistory Building (Old Hospital)', 'Multistory Building (Old Hospital)'), ('Monroe Hill Range', 'Monroe Hill Range'), ('Minor Hall', 'Minor Hall'), ('Monroe Hall', 'Monroe Hall'), ('Maury Hall', 'Maury Hall)'), ('Materials Science Building', 'Materials Science Building'), ('Nau Hall', 'Nau Hall'), ('Newcomb Hall', 'Newcomb Hall'), ('McCormick Observatory', 'McCormick Observatory'), ('Old Cabell Hall', 'Old Cabell Hall'), ('Olsson Hall', 'Olsson Hall'), ('Peabody Hall', 'Peabody Hall'), ('Physics Building', 'Physics Building'), ('Pavilion V (no ADA access)', 'Pavilion V (no ADA access)'), ('Pavilion VIII (no ADA access)', 'Pavilion VIII (no ADA access)'), ('(Randall Hall (first floor only)', '(Randall Hall (first floor only)'), ('National Radio Astronomy Observatory (first floor only)', 'National Radio Astronomy Observatory (first floor only)'), ('Robertson Hall', 'Robertson Hall'), ('Slaughter Recreation Center', 'Slaughter Recreation Center'), ('Ruffner Hall', 'Ruffner Hall'), ('Rice Hall', 'Rice Hall'), ('Rouss Hall', 'Rouss Hall'), ('Rotunda', 'Rotunda'), ('Ruffin Hall', 'Ruffin Hall'), ('Shea House', 'Shea House'), ('Shannon House', 'Shannon House'), ('Slaughter Hall', 'Slaughter Hall'), ('Barracks Stables', 'Barracks Stables'), ('Stacey Hall', 'Stacey Hall'), ('Thornton Hall (D Wing, O Level not accessible)', 'Thornton Hall'), ('Wilson Hall', 'Wilson Hall')], default='None', help_text='Select a meeting spot for your session.', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(default='', help_text='Any additional notes you might have about your request?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='subject',
            field=models.CharField(choices=[('None', 'None'), ('African-american studies', 'African-American & African Studies'), ('Anthropology', 'Anthropology'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('French', 'French'), ('German', 'German'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics')], default='None', help_text='Select a subject that you need help in.', max_length=200),
        ),
    ]
