# Generated by Django 3.0.2 on 2020-03-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20200305_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('none', 'None'), ('african-american studies', 'African-American & African Studies'), ('anthropology', 'Anthropology'), ('astronomy', 'Astronomy'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('economics', 'Economics'), ('french', 'French'), ('german', 'German'), ('physics', 'Physics'), ('mathematics', 'Mathematics')], default='None', max_length=200)),
                ('notes', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
