# Generated by Django 3.0.2 on 2020-03-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20200328_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
