# Generated by Django 3.0.3 on 2020-03-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20200305_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjects_need_help',
            field=models.ManyToManyField(related_name='student_subjects', to='tutor.Subject'),
        ),
    ]
