# Generated by Django 3.0.4 on 2020-03-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20200328_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='default_profile_pic.png', upload_to='media/profile_picture'),
        ),
    ]
