# Generated by Django 3.0.3 on 2020-03-29 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20200329_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_addr',
            field=models.EmailField(default='example@email.com', help_text='Ex: example@email.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='+999999999', help_text="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
