# Generated by Django 3.0.2 on 2020-03-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20200329_1139'),
        ('tutor', '0008_auto_20200329_1357'),
    ]

    operations = [
    ]
