# Generated by Django 3.0.4 on 2020-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20200329_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default_profile_pic.png', upload_to='profile_picture'),
        ),
    ]
