# Generated by Django 3.0.3 on 2020-03-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_auto_20200329_1312'),
        ('tutor', '0009_merge_20200329_1452'),
    ]

    operations = [
    ]
