# Generated by Django 3.0.2 on 2020-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_auto_20200330_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subjects_can_help',
            field=models.ManyToManyField(help_text="Select 'None' if you do not wish to tutor", to='tutor.Subject'),
        ),
    ]
