# Generated by Django 3.0.2 on 2020-04-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_auto_20200406_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
