# Generated by Django 3.0.3 on 2020-04-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_job_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='course',
            field=models.CharField(default='', help_text='Ex: ECON 2010, MATH 1010', max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid course code using following format: TEST 2010 (Make sure to capitalize the course subject!)', regex='[A-Z]{2,4} \\d{4}')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='First', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Last', max_length=30),
        ),
    ]
