# Generated by Django 3.0.4 on 2020-04-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_job_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
