# Generated by Django 3.0.4 on 2020-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_job_iscomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='session_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
