# Generated by Django 3.0.3 on 2020-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_auto_20200411_1351'),
        ('tutor', '0016_auto_20200411_1754'),
    ]

    operations = [
    ]
