# Generated by Django 3.0.3 on 2020-04-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_merge_20200412_0909'),
        ('tutor', '0016_auto_20200413_0809'),
    ]

    operations = [
    ]
