# Generated by Django 3.0.3 on 2020-04-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0021_auto_20200413_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Any additional notes you might have about your request?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjects_can_help',
            field=models.ManyToManyField(help_text="Crtl-click to select multiple subjects; select 'None' if you do not wish to tutor", to='tutor.Subject'),
        ),
    ]
