# Generated by Django 3.0.3 on 2020-04-22 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_auto_20200413_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Any additional notes you might have about your request?', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text="Phone number must be entered in the format: '9999999999'. Up to 15 digits allowed.", max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
