# Generated by Django 3.0.5 on 2020-04-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0026_auto_20200426_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='acceptedjobs',
            new_name='jobinteractions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='requestedjobs',
        ),
    ]
