# Generated by Django 3.0.5 on 2020-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0027_auto_20200426_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobinteractions',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, null=True),
        ),
    ]
