# Generated by Django 3.0.5 on 2020-04-27 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0028_auto_20200426_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_tutored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastTutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
