# Generated by Django 3.0.5 on 2020-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0029_job_last_tutored_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
    ]
