# Generated by Django 3.0.5 on 2020-04-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0030_job_iscanceled'),
        ('tutor', '0024_auto_20200426_1059'),
    ]

    operations = [
    ]
